1st in br1
Aqualang1/final pull request #1
Opened 2023-07-29 21:21 UTC by Aqualang1

2023-08-06 11:43 UTC, kndr23 approved these changes

2023-08-06 11:43 UTC, kndr23 commented on src/components/table/table.js
> +const Table = () => {
It is bad practice to create a lot of same components. Read the topic: https://www.pluralsight.com/guides/how-to-use-the-map()-function-to-export-javascript-in-react

2023-08-11 09:40 UTC, AlexDomianych requested changes

2023-08-11 09:40 UTC, AlexDomianych commented on src/App.js
цей файл можна видалити, а контент перенести у index.js

2023-08-13 16:07 UTC, closed without merging