modal window
Aqualang1/final pull request #8
Opened 2023-08-30 15:06 UTC by Aqualang1

modal window

2023-08-31 13:27 UTC, AlexDomianych requested changes

2023-08-31 13:27 UTC, AlexDomianych commented on src/components/Modal/Modal.js
> +
зайвий відступ

2023-08-31 13:27 UTC, AlexDomianych commented on src/components/Modal/Modal.js
> +            <b>Delete product {productId}?</b>
тут краще показати не айді продукта, а назву. А ще краще і айді і назву. Це суто з точки зору користувача

2023-08-31 13:27 UTC, AlexDomianych commented on src/components/TableWrapper/TableWrapper.js
> +            const response = await fetch(API_URL + '/' + id, {
`            const response = await fetch('${API_URL}/${id}', {`
шаблонні строки замість конкатинації

2023-08-31 13:27 UTC, AlexDomianych commented on src/components/TableWrapper/TableWrapper.js
> +                setProducts(products.filter((el) => el.id !== id));
у разі успішного видалення бажано не профільтрувати продукти на фронті, а зробити GET запит для отримання списку заново.

2023-09-02 18:09 UTC, GeFeSTTS commented on src/components/ModalDeleteProduct/ModalDeleteProduct.js
> +        <b>Delete product ID {productId} {category} ?</b>
я мав на увазі name, а не category

2023-09-02 22:49 UTC, merged